#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
  path: /login
  controller: App\Controller\LoginController::index

registration:
  path: /registration
  controller: App\Controller\RegistrationController::register

profiel:
  path: /profile
  controller: App\Controller\TodoController::index
